plaid:
  client_id: "your_plaid_client_id"
  secret: "your_plaid_secret"
  access_token: "your_plaid_access_token"

email:
  smtp_server: "smtp.gmail.com"
  username: "your_email@gmail.com"
  password: "your_app_specific_password"
  from_email: "your_email@gmail.com"

sms:
  account_sid: "your_twilio_account_sid"
  auth_token: "your_twilio_auth_token"
  from_number: "+1234567890"

users:
  - email: "user1@example.com"
    phone: "+1234567890"
  - email: "user2@example.com" 